---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Get a message with a fur color

You can get a message with the fur color of interest with `get_message_fur_color()`.

```{r function-get_message_fur_color}
#' Get a message with the fur color of interest
#'
#' @param primary_fur_color Character. The primary fur color of interest
#' @importFrom glue glue
#' 
#' @return Used for side effect. Outputs a message in the console
#' @export
#'
#' @examples
get_message_fur_color <- function(primary_fur_color) {
  message(glue("We will focus on {primary_fur_color} squirrels"))
}
```

```{r example-get_message_fur_color}
get_message_fur_color(primary_fur_color = "Cinnamon")
```

```{r tests-get_message_fur_color}
test_that("get_message_fur_color works", {
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Cinnamon"), 
    regexp = "We will focus on Cinnamon squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Gray"), 
    regexp = "We will focus on Gray squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Black"), 
    regexp = "We will focus on Black squirrels"
  )
  
})

test_that("get_message_fur_color doesnt works", {
  
  expect_error(
    get_message_fur_color()
  )
  
})
```


# check_primary_color_is_ok

```{r function-check_primary_color_is_ok}
#' Check the values of primary fur color
#'
#' @param string Character. A vector with the primary fur color.
#'
#' @return Boolean. TRUE if all colors are correct.
#' @export
#'
#' @examples
check_primary_color_is_ok <- function(string) {
  all_colors_OK <- all(
    string %in% c("Gray", "Cinnamon", "Black", NA)
  )
  return(all_colors_OK)
}
```

```{r example-check_primary_color_is_ok, eval=FALSE}
check_primary_color_is_ok("Cinnamon")
```

```{r tests-check_primary_color_is_ok}
test_that("check_primary_color_is_ok works", {
  expect_true(inherits(check_primary_color_is_ok, "function")) 
  expect_true(object = check_primary_color_is_ok("Cinnamon"), TRUE)
  expect_false(object = check_primary_color_is_ok("dsdsds"), FALSE)
  
})
```

# check_squirrel_data_integrity

```{r function-check_squirrel_data_integrity}
#' Function to check squirrel data integrity
#' @param data_df Squirrel dataset
#' 
#' @return String returns a message with the data integrity information
#' 
#' @export 
#' 
#' @examples
check_squirrel_data_integrity <- function(data_df){
  
  if ("primary_fur_color" %in% names(data_df)){
    res <- check_primary_color_is_ok(data_df$primary_fur_color)
    if(isTRUE(res)){
      message("All primary colors are correct")
    }else{
      message("Not all primary colors correct")
    }
    
    
  }else{
    stop("primary_fur_color column not fount in the dataset")
  }
  
  
}
```


```{r example-check_squirrel_data_integrity}
data_path <- system.file("nyc_squirrels_act_sample.csv", package="squirrels")
data_act_squirrels <- readr::read_csv(data_path)
check_squirrel_data_integrity(data_act_squirrels)
```

```{r tests-check_squirrel_data_integrity}
test_that("check_squirrel_data_integrity works",
          {
            my_data <- readr::read_csv(
              file = system.file("nyc_squirrels_sample.csv",package="squirrels")
            )
            
            expect_message(check_squirrel_data_integrity(my_data),
                           regexp = "All primary colors are correct"
                           
            )
            # Error: no primary_fur_color column in the dataset
            
          })
```


# study_activity

```{r function-study_activity}
#' Study the activities of the squirrels given a primary fur color
#'
#' @param df_squirrels_act Data frame. A dataset with the activities of the squirrels. This dataset mush have at leat these 4 columns: "age", "primary_fur_color", "activity", "counts".
#' @param col_primary_fur_color Character. The color of the primary fur color of interest. Only the squirrels with this primary fur color will be considered in the analysis.
#' 
#' @importFrom dplyr filter
#' @importFrom ggplot2 ggplot aes geom_col scale_fill_manual labs
#' @importFrom magrittr %>% 
#'
#' @return A list of two named elements. The first one is the filtered table. The second one is the ggplot.
#' @export
#'
#' @examples
study_activity <- function(df_squirrels_act, col_primary_fur_color) {
  
  if(isFALSE(check_squirrel_data_integrity(df_squirrels_act))){
    stop("df_squirrels_act fails integrity test")
    
  }
  
  if(isFALSE(is.data.frame(df_squirrels_act))) {
    stop("df_squirrels_act is not a data frame")
  }
  
  if(isFALSE(is.character(col_primary_fur_color))) {
    stop("col_primary_fur_color is not a character vector")
  }
  
  
  table <- df_squirrels_act %>% 
    filter( col_primary_fur_color == primary_fur_color)
  
  graph <- table %>% 
    ggplot() +
    aes(x = activity, y = counts, fill = age) +
    geom_col() +
    labs(x = "Type of activity",
         y = "Number of observations",
         title = glue("Type of activity by age for {tolower(col_primary_fur_color)} squirrels")) +
    scale_fill_manual(name = "Age",
                      values = c("#00688B", "#00BFFF"))
  
  return(list(table = table, graph = graph))
}
```

```{r example-study_activity}
data_path <- system.file("nyc_squirrels_act_sample.csv", package="squirrels")
data_act_squirrels <- readr::read_csv(data_path)
study_activity(
  df_squirrels_act = data_act_squirrels,
  col_primary_fur_color = "Gray"
)
```


```{r tests-study_activity}
test_that("study_activity works", {
  
  test_data_path <- system.file("nyc_squirrels_act_sample.csv", package="squirrels")
  test_data_df <- readr::read_csv(data_path)
  
  
  
  expect_true(inherits(study_activity, "function")) 
})
```



```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_study_squirrels.Rmd", 
  vignette_name = "Study the squirrels",
  overwrite = TRUE
)
```
