# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

test_that("study_activity works", {
  
  test_data_path <- system.file("nyc_squirrels_act_sample.csv", package="squirrels")
  test_data_df <- readr::read_csv(data_path)
  
  
  
  expect_true(inherits(study_activity, "function")) 
})
