# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

test_that("check_primary_color_is_ok works", {
  expect_true(inherits(check_primary_color_is_ok, "function")) 
  expect_true(object = check_primary_color_is_ok("Cinnamon"), TRUE)
  expect_false(object = check_primary_color_is_ok("dsdsds"), FALSE)

})
