# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

#' Function to check squirrel data integrity
#' @param data_df Squirrel dataset
#' 
#' @return String returns a message with the data integrity information
#' 
#' @export 
#' 
#' @examples
#' data_path <- system.file("nyc_squirrels_act_sample.csv", package="squirrels")
#' data_act_squirrels <- readr::read_csv(data_path)
#' check_squirrel_data_integrity(data_act_squirrels)
check_squirrel_data_integrity <- function(data_df){
  
  if ("primary_fur_color" %in% names(data_df)){
    res <- check_primary_color_is_ok(data_df$primary_fur_color)
    if(isTRUE(res)){
      message("All primary colors are correct")
    }else{
      message("Not all primary colors correct")
    }
    
    
  }else{
    stop("primary_fur_color column not fount in the dataset")
  }
  
  
}
