# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

#' Get a message with the fur color of interest.
#' 
#' Get a message with the fur color of interest.
#' 
#' @param primary_fur_color Character. The primary fur color of interest
#' @importFrom glue glue
#' @return Nothing Used for side effect. Outputs a message in the console
#' 
#' @export
#' @examples
#' get_message_fur_color(primary_fur_color = "Cinnamon")
get_message_fur_color <- function(primary_fur_color){
  color_ok <- check_primary_color_is_ok(primary_fur_color)
  if(isTRUE(color_ok)){
     message(glue("We will focus on {primary_fur_color} squirrels"))
  }
  else{
    stop("Incorrect color provided")
  }
   
}
